Productのハッシュタグの表示UI
ProgateHackathon/Gitagram pull request #101
Opened 2024-06-30 09:56 UTC by urassh

## やったこと
- 各Productの持っているハッシュタグを表示できるようにした。
- HashTagをHashableに準拠させた

## 影響範囲
- CardView
- HashTag
- HashTagView

## スクリーンショット
| ハッシュタグなし | ハッシュタグあり |
|--------|--------|
| <img width="323" alt="スクリーンショット 2024-06-30 18 52 54" src="https://github.com/ProgateHackathon/Gitagram/assets/84073765/1fc3b027-41c6-4e75-97bd-faf74d2b27a0"> | <img width="317" alt="スクリーンショット 2024-06-30 18 54 29" src="https://github.com/ProgateHackathon/Gitagram/assets/84073765/101c063a-3f4c-4099-b201-9ef7e8e3e0c0"> | 

## 動作確認
- iOS18 simulatorにて動作確認済み

close #

2024-06-30 10:04 UTC, urassh commented
あ、やべ。ブランチ切るの忘れてた。
一旦このままmainにマージさせる方向でいいや

2024-07-01 00:19 UTC, am2525nyan requested changes
えらー出てて、新しくリポジトリ追加してもタグ追加されてない（そもそもリポジトリが表示されていない）ので、確認お願いします！！
getで出てたやつ↓
`Error decoding city: valueNotFound(Swift.KeyedDecodingContainer<Gitagram.HashTagResponse.(unknown context at $101817108).CodingKeys>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Cannot get keyed decoding container -- found null value instead.", underlyingError: nil))`

2024-07-01 02:34 UTC, urassh commented
@am2525nyan 
あ、そうじゃん。！
今回のPRとは関係ないエラーだから別PRで対応しよっか

2024-07-01 02:39 UTC, am2525nyan commented
OKですー！

> 新しくリポジトリ追加してもタグ追加されてない（そもそもリポジトリが表示されていない）ので、確認お願いします！！
こっちはこのPRであってます？別？

2024-07-02 15:39 UTC, merged