Feature/#55 change add repository view
ProgateHackathon/Gitagram pull request #63
Opened 2024-05-15 15:15 UTC by am2525nyan

## やったこと
ハッシュタグの設定画面、選択できるようにした

## 影響範囲
postRepositoryView
## 補足
モデル周り触ってません
コメントアウトでmodelできたらこうしたいなーーみたいなの書いてあります
modelできるまでは一旦ランダムで代入してます
## スクリーンショット
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/8abffc41-58a5-4fb3-9a5f-fbe70b1cd2d8  width=30%>
## 動作確認
動きます！
close #55

2024-05-15 15:26 UTC, am2525nyan commented on Gitagram/View/PostView/PostHashTagView.swift
> +        .background(Color(red: CGFloat.random(in: 0.7...1), green: CGFloat.random(in: 0.7...1), blue: CGFloat.random(in: 0.7...1)).gradient)
@urassh 
『質問』
今リポジトリの登録画面でハッシュタグを選べるようにUI作っているのですが、ハッシュタグの背景色が一色だとみづらいかなと思ってとりあえずランダムに明るめの色が出るようにしているのですが、これってハッシュタグに対して色固定(firebaseに色も保存)の方がいいですか、、？
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/9b437b9a-597d-4302-8a66-a6d483b10979  width=20%>

2024-05-15 15:27 UTC, am2525nyan commented on Gitagram/View/PostView/PostHashTagView.swift
> +        .background(Color(red: CGFloat.random(in: 0.7...1), green: CGFloat.random(in: 0.7...1), blue: CGFloat.random(in: 0.7...1)).gradient)
あとこういう実装内容の話ってプルリクで投げるかdiscordで投げるかメッセとかかどれがいいですか！？

2024-05-15 15:27 UTC, urassh commented on Gitagram/View/PostView/PostHashTagView.swift
> +        .background(Color(red: CGFloat.random(in: 0.7...1), green: CGFloat.random(in: 0.7...1), blue: CGFloat.random(in: 0.7...1)).gradient)
@am2525nyan 
あー、そうだね！
ハッシュタグにカラーコードを載せる感じにするか！

2024-05-15 15:28 UTC, urassh commented on Gitagram/View/PostView/PostHashTagView.swift
> +        .background(Color(red: CGFloat.random(in: 0.7...1), green: CGFloat.random(in: 0.7...1), blue: CGFloat.random(in: 0.7...1)).gradient)
@am2525nyan 
俺的には、Draftの方が見やすくて助かる！

2024-05-23 05:31 UTC, urassh requested changes
@am2525nyan 
とりあえずレビュー書いてみました！
まだ書ききれていない部分があるかもだけど、とりあえずこの修正をお願いします🙏

意識して欲しいことが、使っていない変数は必要なものを勘違いしてしまう可能性があるから速やかに消しておく...です!!

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostView.swift
>      @State var next = false
ここのnext使っていないので消しましょう！！

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostDiscriptionView.swift
[must]
- next変数は使われていないので消しましょう!!

[more]
- Discription -> Description かな🤔

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostDiscriptionView.swift
> +                PostURLView(title: $title, discription: $discription, developer: Developer(githubId: ""))
[must]空のDeveloperを渡すのもうやめても良いです!!

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostURLView.swift
>      @State var next = false
[must] ここのnextも使われていないので消しましょう!!

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostURLView.swift
>                  Text("リポジトリのリンクは？")
[discuss]
ここ、リンク打たせるの流石にきついからリポジトリ名入力にしておきません？
urlは以下の感じにすると作成できるので🙌

repository URL : `https://github.com/{developer}/{repository name}`

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostURLView.swift
>      @State var developer : Developer
[must] ここのdeveloperも使われていないので、変数を削除してしまいましょう！！

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostURLView.swift
> +                    PostHashTagListView(title: $title, discription: $discription, developer: Developer(githubId: ""), url: $url)
[must] ここもからのDeveloperを渡すのやめましょう!!

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostHashTagListView.swift
> +    @State var developer : Developer
[must] このdeveloperも渡すだけで使ってはいないから削除しよっか！

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostHashTagListView.swift
> +    @State var next = false
[must]
このnextも使われていないから削除しましょう🙌

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostHashTagListView.swift
> +                PostImageView(developer: Developer(githubId: ""), title: $title, discription: $discription, url: $url)
[must]
ここも空のdeveloperを渡すのやめましょうー！

2024-05-23 05:31 UTC, urassh commented on Gitagram/View/PostView/PostImageView.swift
[must]
- developer変数受け取ったの結局 空のオブジェクトだから以下の　どっちかで変更してほしい！
1. developerの型をオプショナル型にする。
2. 宣言時に直接空のDeveloper(githubId: "")を代入する。

[suggest]
- next変数の切り替えでPostProductUseCaseを実行しているのだけれど、これ保存ボタンに直接書くでも良さそうじゃない？

2024-05-30 08:52 UTC, am2525nyan commented on Gitagram/View/PostView/PostView.swift
>      @State var next = false
next、39行目あたりでnavigationリンクの遷移で使ってます！

2024-05-30 08:52 UTC, am2525nyan commented on Gitagram/View/PostView/PostDiscriptionView.swift
こちらもnext、navigationリンクの遷移で使ってます！

2024-05-30 08:52 UTC, am2525nyan commented on Gitagram/View/PostView/PostURLView.swift
>      @State var next = false
こちらもnext、navigationリンクの遷移で使ってます！

2024-05-30 08:56 UTC, am2525nyan commented on Gitagram/View/PostView/PostView.swift
>      @State var next = false
いたブランチが違ってました！！消します！

2024-06-02 11:28 UTC, am2525nyan commented on Gitagram/View/PostView/PostURLView.swift
>                  Text("リポジトリのリンクは？")
https://github.com/ProgateHackathon/Gitagram/pull/63/commits/e43bc441a1553c17560d6c96b2700c7f4d3ebc19
で修正しました！

2024-06-02 11:29 UTC, am2525nyan commented on Gitagram/View/PostView/PostURLView.swift
> +                    PostHashTagListView(title: $title, discription: $discription, developer: Developer(githubId: ""), url: $url)
https://github.com/ProgateHackathon/Gitagram/commit/e43bc441a1553c17560d6c96b2700c7f4d3ebc19
で直しました！！！！

2024-06-02 11:30 UTC, am2525nyan commented on Gitagram/View/PostView/PostHashTagListView.swift
> +    @State var developer : Developer
https://github.com/ProgateHackathon/Gitagram/commit/e43bc441a1553c17560d6c96b2700c7f4d3ebc19
で直しました！！！！

2024-06-02 11:31 UTC, am2525nyan commented on Gitagram/View/PostView/PostImageView.swift
https://github.com/ProgateHackathon/Gitagram/commit/e43bc441a1553c17560d6c96b2700c7f4d3ebc19
ボタンに直書きしました！
2で実装しました！

2024-06-02 11:31 UTC, am2525nyan commented
プルリク分け忘れましたすみません！！！
全て修正してあります！！！！！！！！！！
https://github.com/ProgateHackathon/Gitagram/commit/e43bc441a1553c17560d6c96b2700c7f4d3ebc19
@urassh

2024-06-03 04:41 UTC, am2525nyan commented
矛盾オブ矛盾なんですが、ハッシュタグ追加機能一旦いらない気がしてきました
被りswiftとSwiftとかあったら大変そうだなーーーって

2024-06-03 10:52 UTC, urassh commented
@am2525nyan 
まぁ確かに一旦リリースしてからでも良いかもだなぁ
Discordの会議チャンネルで一旦聞いてみよー！

ハッシュタグ機能実装スキルアップしそうな気もしてて笑

2024-06-04 01:32 UTC, am2525nyan commented
２回目(３回目?)のリリースで追加機能は実装で、今回はこっちが決めたリスト内にあるタグから選択する形でどうでしょう！！
とりあえずディスコにも投げます！

2024-06-07 11:19 UTC, am2525nyan commented
@urassh 
やっと全て直しました！！！とりあえず仮でモデルあるんですが無視で！
cardViewのタグは一旦swiftつっこんであります
ハッシュタグ一覧に入れるタグ募集してます


<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/063bcc83-b4c7-469c-b1c9-0be23c63191b  width=30%>

2024-06-07 11:20 UTC, am2525nyan commented
あとPost周りの上のプログレスバーいい感じにパーセント直したんですがなんかどうしてもキモいのでいつかなんとかしたいです

2024-06-10 02:30 UTC, urassh commented
@am2525nyan 
この画面リンク入力させるのはしんどいと思うから、初期値として、以下のような文字列を初期値として入れてあげるのが親切な気がする！
`https://github.com/urassh/` 

<img width="323" alt="スクリーンショット 2024-06-10 11 28 09" src="https://github.com/ProgateHackathon/Gitagram/assets/84073765/e89722ff-6bb7-4727-a0fe-7f34d665ddc7">

2024-06-10 02:30 UTC, urassh commented
それ以外はLGTMです!!

2024-06-10 02:45 UTC, urassh approved these changes

2024-06-10 02:46 UTC, am2525nyan commented
@urassh 
https://github.com/ProgateHackathon/Gitagram/pull/63#issuecomment-2157080620
内部ではhttps://github.com/urassh/のあとだけ入力の形になってます！UI直し忘れてたので修正します！

2024-06-10 06:54 UTC, am2525nyan commented
コンフリクトしてなくて嬉しい

2024-06-13 00:56 UTC, merged