fix-openURL
ProgateHackathon/Gitagram pull request #70
Opened 2024-05-22 04:20 UTC by am2525nyan

## やったこと
URLが登録されていない時に、アラートが出て落ちないようにした。
## 影響範囲

## 補足

## スクリーンショット
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/004b5f20-e75b-4efc-bc38-f1ca6440b362  width=30%>

## 動作確認

close #69

2024-05-23 05:56 UTC, urassh requested changes
一箇所指摘したけど、それ以外はLGTMです!!

2024-05-23 05:56 UTC, urassh commented on Gitagram/View/MatchingView/Component/CardView.swift
> +            isShowAlert.toggle()
[more]
ここの処理の意図はtoggleを切り替えるというよりは、アラートを出すという意図と伝えたいから、trueを代入する書き方にした方がわかりやすいかも。
```suggestion
            isShowAlert = true
```

2024-05-30 08:49 UTC, am2525nyan commented on Gitagram/View/MatchingView/Component/CardView.swift
> +            isShowAlert.toggle()
https://github.com/ProgateHackathon/Gitagram/pull/70/commits/1c3ab77b4ab19df97f25ea3317bcc693e4b85209
で修正しました！
@urassh

2024-06-10 02:32 UTC, urassh approved these changes
@am2525nyan 
こちらApprove出します！！
このPRはMergeして大丈夫です！！

2024-06-10 03:44 UTC, merged