add-preview-image
ProgateHackathon/Gitagram pull request #71
Opened 2024-05-22 05:03 UTC by am2525nyan

## やったこと
リポジトリ追加画面の画像追加のとこで画像のプレビューを表示できるようにした
## 影響範囲

## 補足

## スクリーンショット
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/b0ec9700-cfc8-4ecc-86ee-0562894026b4  width=30%>

## 動作確認
動いた、画像変更してもちゃんと変わった
close #52

2024-05-23 06:14 UTC, urassh requested changes
レビュー完了しました！
指摘箇所の修正お願いします!!

2024-05-23 06:14 UTC, urassh commented on Gitagram/View/PostView/PostImageView.swift
> +                    await loadImageFromSelectedPhoto(photo: selectedPhoto)
[imo]
これLoadImageFromLibraryUseCaseで実装しても良さそうだね。
```LoadImageFromLibraryUseCase.swift
class LoadImageFromLibraryUseCase {
    func execute(_ pickerItem: PhotosPickerItem) async -> UIImage? {
        if let data = try? await pickerItem?.loadTransferable(type: Data.self) {
            return UIImage(data: data)
        }

        return nil;
    }
}
```

```suggestion
 .onChange(of: selectedPhoto) { selectedPhoto in
        Task { 
            self.image = await LoadImageFromLibraryUseCase().execute(selectedPhoto)
        }
}
```

2024-05-23 06:14 UTC, urassh commented on Gitagram/View/PostView/PostImageView.swift
> +            .onChange(of: selectedPhoto) { newItem in
[must]
多分、同じこと2回してる。

`Dont Repeat Yourself`だ👍
`🔍 DRY原則`

2024-05-30 08:36 UTC, am2525nyan commented
@urassh 
https://github.com/ProgateHackathon/Gitagram/pull/71/commits/36002ed33f082cec74fc77ff0fbaa019d38aed7f
で全部修正しました！！！！！！！！遅くなってすみません！！！！！！

2024-06-10 02:42 UTC, urassh approved these changes
修正確認しました！！
Approve出したのでMergeしちゃってください！

2024-06-10 03:44 UTC, merged