Feature/#58 add GitHub login
ProgateHackathon/Gitagram pull request #88
Opened 2024-06-20 17:31 UTC by am2525nyan

## やったこと
firebase authを使って、githubログインができるようにした！
githubAPIを使って、ユーザー名取得、その後developerを作ってます！(inputview)の時の挙動と同じ

## 影響範囲
developer
## 補足

- 一応動くか確認のため一旦ログインできるか手元で確認してほしいです！

gitHubログインをするボタンがあるページのUI手ほぼつけれてないので、@Rino1011 か 手空いてたら @urassh やってほしいです！！
## スクリーンショット
とりあえず並べてみたUI
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/8ebe880f-1e6d-4661-9518-f3149298c746  width=30%>

## 動作確認
ログインできた
close #58

2024-06-20 17:33 UTC, am2525nyan commented
コンフリクトがInfo.plistで起きてた、治ってますように、、、、

2024-06-25 15:39 UTC, urassh requested changes
@am2525nyan 
遅くなってごめんレビュー返しました!!
2点の修正をお願いします...!!

以下は修正しなくても良いけど、全体的に思ったこと。
---
ViewModelの役割がModelと被ってたことかな。
ViewModelって、Viewの状態管理をしつつ、ModelとViewの仲介を行う役目なのよな。
今回たまたま、ModelがSignInで、LoginViewでしか使われないから問題はなさそうだけど、本来はModelにFirebaseの実装を追いやるのが理想。

---
MVVMについてちょっと書いてみた。

### MVVMの良いとこ
1. ModelはViewに依存せず機能の実装だけ考えればよい。
2. ViewModelで、Viewで使うModelを巻取りつつ、View特有の状態管理と噛ませることができる。
3. Viewは表示するUIのことだけ考えれば良い(機能詳細や状態管理はViewModelの仕事)

### MVVMの弱点
状態管理がView単位になってしまう。(ログインしているユーザーは共通だけど、Viewが変更される度にModelにアクセスしなきゃ行けなくなっちゃう / または値渡しするかだな)
これはめちゃ実感しているんじゃないかな。

2024-06-25 15:39 UTC, urassh commented on Gitagram/View/LoginView/LoginViewModel.swift
> +    @State var provider = OAuthProvider(providerID: "github.com")
@am2525nyan
ここ、@State にしなくても良さそうー！
letでいけそう

2024-06-25 15:39 UTC, urassh commented on Gitagram/View/LoginView/LoginView.swift
> +    @State var isUserLoggedIn = Auth.auth().currentUser != nil
view側でisUserLoggedInは、viewmodelに書いた方が良いかも！
viewmodelで@Published使えば行けたはず。

2024-06-25 15:43 UTC, urassh commented on Gitagram/View/LoginView/LoginViewModel.swift
> +    @State var provider = OAuthProvider(providerID: "github.com")
```suggestion
    let provider = OAuthProvider(providerID: "github.com")
```

2024-06-26 00:53 UTC, am2525nyan commented
@urassh
うわーーーー！めちゃめちゃわかりやすい！！！！ありがとうございます！！MVVMなんとなーーくわかった気になってたんですけど、すごいよくわかりました、、、、、
swiftのアーキテクチャの最適解ってなんでしょうね😔
弱点確かに、、、いちいちDeveloperとってきてますもんね

2024-06-26 00:53 UTC, am2525nyan commented
あとログイン動いてましたー？！

2024-06-26 01:07 UTC, am2525nyan commented on Gitagram/View/LoginView/LoginView.swift
> +    @State var isUserLoggedIn = Auth.auth().currentUser != nil
https://github.com/ProgateHackathon/Gitagram/pull/88/commits/9fb682608a2d742585154d53a70431632973abe5
で修正しました！

2024-06-26 03:09 UTC, urassh commented
@am2525nyan 
ごめん、書き忘れてたわ。
ログインはできているけど、isLoggedInの更新がされていない感じやな。
currentUserのアクセスが最初の一回のみだからかな。

2024-06-26 12:51 UTC, urassh approved these changes
[Approve]
コンフリクト解消したらOK!!

2024-06-26 13:01 UTC, merged