カード周りの実装
ProgateHackathon/Gitagram pull request #89
Opened 2024-06-21 16:53 UTC by Rino1011

## やったこと
- カードデザインを選択できるようにしました
- カードデザイン二つ目を追加しました
- ファイル構造を綺麗にしました

## 影響範囲
AccountViewフォルダの中

## 補足

## スクリーンショット

## 動作確認

close #86

2024-06-22 13:32 UTC, am2525nyan requested changes
何個か！確認と修正お願いします！！！

2024-06-22 13:32 UTC, am2525nyan commented on Gitagram/View/AccountView/AccountView.swift
must
字数長い時に二行になっちゃってちょっと残念かんあるので、一行に収まるように長さによって文字サイズが可変するようにしてほしい！
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/9eb77803-cd36-4bc3-9080-cf56ddf6d623  width=30%>

<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/37cd7e6b-e206-46bd-b0ec-044c3e7ae1ce  width=30%>

2024-06-22 13:32 UTC, am2525nyan commented on Gitagram/View/AccountView/AccountView.swift
> +                        Text("Gitagram")
gitagramの文字なくてもいいかもしれない or フォント変えたらいい感じ or 初期gitagramロゴ置いたらいい感じかも　＋
せっかく上に共有ボタンを置いてるので、 ToolbarItemを使ってほしい！

2024-06-22 13:32 UTC, am2525nyan commented on Gitagram/View/AccountView/CardDesign/AccountCardTypeTwoView.swift
質問
雲と虹おいてない認識で合ってるー？

2024-06-22 13:32 UTC, am2525nyan commented on Gitagram/View/AccountView/CardDesign/AccountCardTypeTwoView.swift
ちょっとだけ寂しいのでおきたいかも！

2024-06-22 13:32 UTC, am2525nyan commented on Gitagram/View/AccountView/CardDesign/AccountCardTypeTwoView.swift
> +//綺麗め！ざシンプル！
must
消そう！
```suggestion

```

2024-06-22 13:33 UTC, am2525nyan commented on Gitagram/View/AccountView/AccountView.swift
> +                        Text("Gitagram")
初期ロゴ置くのが一番いい感じ？任せる！

2024-06-22 13:39 UTC, am2525nyan requested changes
これも！変更よろしくお願いします！！

2024-06-22 13:39 UTC, am2525nyan commented on Gitagram/Model/UseCase/Util/TakeScreenShotUseCase.swift
> -//  TakeScreenShotUseCase.swoft.swift
めちゃめちゃ笑ったナイス気づき！

2024-06-22 13:39 UTC, am2525nyan commented on Gitagram/View/AccountView/Component/QRDesign/QRTypeOneView.swift
> +        .background(Color("FrameBrownColor"))
must
FrameBrownColorがcolorでなくてエラー出てるので変更お願いします！！！

2024-06-22 13:41 UTC, am2525nyan commented
@Rino1011 githubログイン対応させたことによって、わんちゃんdeveloper死ぬかもなのでどこでID取得してるか教えてほしい！

2024-06-26 06:02 UTC, Rino1011 commented on Gitagram/View/AccountView/AccountView.swift
実装できました、、、！

2024-06-26 06:02 UTC, Rino1011 commented on Gitagram/View/AccountView/AccountView.swift
> +                        Text("Gitagram")
いらないかなってなったから消しました！

2024-06-26 06:03 UTC, Rino1011 commented on Gitagram/View/AccountView/CardDesign/AccountCardTypeTwoView.swift
みのりんさんがデザインしてくれたカードになかったから入れてなかった、、、
もう一個デザインしてもらってたからカードデザイン増やしてそこに虹と雲入れました！！

2024-06-26 06:04 UTC, Rino1011 commented on Gitagram/View/AccountView/CardDesign/AccountCardTypeTwoView.swift
> +//綺麗め！ざシンプル！
忘れてたごめんなさい消しました笑

2024-06-26 06:05 UTC, Rino1011 commented on Gitagram/View/AccountView/Component/QRDesign/QRTypeOneView.swift
> +        .background(Color("FrameBrownColor"))
ごめんなさい！直しました！

2024-06-26 06:09 UTC, Rino1011 commented
レビュー反映させました、、！
カードのデザイン3つ目あるんですけどそのテキストの歪ませるの、？が実装できなくて、、🙏🏻
![image](https://github.com/ProgateHackathon/Gitagram/assets/156809496/c4e5fb46-0e94-4176-b9dc-f2f1aef8abd9)
それができてないだけだと思います、、！

2024-07-01 01:32 UTC, am2525nyan reviewed
修正ありがとー！
ちょっとここだけ気になったので見てほしい！中にpaddingつけるとかかなー
コードよんでないです🥺多分きっと大丈夫だと思いたいです
あと、コンフリクト起こってるからmainブランチpullしてマージして解消してほしい！難しかったらメッセで呼んでー！一緒になおそ

<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/9f75740c-88b4-417c-98f9-2dc41ca00b93  width=20%>
<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/d408080b-1209-4b6b-9d42-6404b0a941a6  width=20%>

2024-07-01 01:32 UTC, am2525nyan commented on Gitagram/View/AccountView/Component/ImageDesign/ImageCloudView.swift
> +            //.padding(.leading,0)
must 
消そー！！！

2024-07-12 04:10 UTC, am2525nyan commented
@Rino1011 これもう終わってる認識で合ってる？

2024-07-12 04:11 UTC, Rino1011 commented
終わってます！

2024-07-12 04:15 UTC, am2525nyan commented
ないす！ありがとう！夜見ます！

2024-07-13 04:26 UTC, am2525nyan commented
@Rino1011 
プロジェクト今見れる？？コンフリクト解消できてない説ある。。。

2024-07-13 04:27 UTC, am2525nyan commented
or　変更後pushした！？

2024-07-13 05:06 UTC, am2525nyan requested changes
改行警察します！👮ふぁいとー！

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/KiraKira/KiraKiraDesign/KiraKiraTypeThreeView.swift
> +                .opacity(viewModel.frontImageOpacitry)
nits 
改行気になるな！

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/KiraKira/KiraKiraDesign/KiraKiraTypeThreeView.swift
> +                .opacity(viewModel.middleImageOpacity)
ここも改行！気になる！

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/KiraKira/KiraKiraDesign/KiraKiraTypeThreeView.swift
> +            Image("kirakira")
もはやこっちを改行したい
```suggestion

            Image("kirakira")
```

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/KiraKira/KiraKiraDesign/KiraKiraTypeTwoView.swift
> +                .opacity(viewModel.middleImageOpacity)
改行〜

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/KiraKira/KiraKiraDesign/KiraKiraTypeTwoView.swift
> +                .opacity(viewModel.frontImageOpacitry)
ここも！

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/KiraKira/KiraKiraDesign/KiraKiraTypeTwoView.swift
> +            BackTypeTwoView()
ここー！

2024-07-13 05:06 UTC, am2525nyan commented on Gitagram/View/AccountView/Component/TextDesign/FrankfrtText.swift
> +            .foregroundColor(Color("TextPurpleColor"))
改行警察です

2024-07-14 00:10 UTC, am2525nyan commented
#125 に移行したので閉じます

2024-07-14 00:10 UTC, closed without merging