Developerの不具合修正
ProgateHackathon/Gitagram pull request #92
Opened 2024-06-22 12:50 UTC by urassh

## やったこと
- CardDataが持つDeveloperがわかりにくい名前なので、"loginHostにした"
- productのDeveloperが代入されていなかったのでその修正。
- 若干、PostURLViewのリファクタリング
- ProductでsetDeveloperメソッドの追加

## 影響範囲
- CardDataでDeveloperを使っている箇所全て
- PostURLView

## 補足
- 特になし。

## スクリーンショット

## 動作確認
- 送信時にしっかりDeveloperの情報が残っていることを確認、

close #

2024-06-22 12:53 UTC, am2525nyan commented on Gitagram/Model/DataModel/Entity/CardData.swift
> +    let loginHost : Developer
これ最高です

2024-06-22 13:04 UTC, am2525nyan requested changes
product Clientの29行目のcreateのとこでproduct.id.uuidStringをdocumentに入れてると思うんですが、そもそものproductIdが0000-000〜になってしまっているのでproductId生成周りfirebaseが常に上書きされちゃってるので確認してほしいです！
あとfirebaseのdeveloper idってfirebaseのdevelopersの名前ですか？！

それ以外は大丈夫です！

2024-06-22 13:15 UTC, urassh commented
@am2525nyan 
ほんとだ。。。。
色々やらかしてすみませんー！！！！！！！！！
直しますー！

2024-06-22 13:17 UTC, urassh commented
> developer idってfirebaseのdevelopersの名前ですか？
DeveloperIdはUUIDだと思う！

2024-06-22 13:18 UTC, urassh commented on Gitagram/Model/DataModel/Entity/CardData.swift
> +    let loginHost : Developer
@am2525nyan 
名前が大事ってことが身に染みるぜ...😎

2024-06-22 13:45 UTC, am2525nyan commented
https://github.com/ProgateHackathon/Gitagram/pull/92#issuecomment-2184029307
なるほど！？今のfirebaseってこうなってると思うんですが、UUIDだとloginhostが紐づかないかもしれないです！！！！
```
content
"Aa"


developerId
"9C2B3384-162F-4EF3-980B-6DD81B724B7C"
（文字列）

id
"00000000-0000-0000-0000-000000000000"
（文字列）

title
"Amam"
（文字列）

url
"https://github.com/am2525nyan/Amam"
（文字列）

```

2024-06-22 13:51 UTC, urassh commented
@am2525nyan 
おけおけ！！
とりあえず、今日は疲れたので明日しっかり見ますね！！

2024-06-22 13:51 UTC, am2525nyan reviewed
カードリロードしても、追加したリポジトリ表示されないので、これも確認お願いします！！！！

2024-06-22 13:51 UTC, am2525nyan commented on Gitagram/Model/DataModel/Entity/Product.swift
> +        Product(title: "", content: "", developerId: DeveloperID.Empty(), url: "", hashTags: [])
firebase上でも確認できましたー！ナイスです

2024-06-23 14:52 UTC, urassh commented on Gitagram/Model/DataModel/Entity/Product.swift
> +        Product(title: "", content: "", developerId: DeveloperID.Empty(), url: "", hashTags: [])
@am2525nyan 
言いたいことがすごいわかりました！
なおしますー！

2024-06-23 15:10 UTC, urassh commented on Gitagram/Model/DataModel/Entity/Product.swift
> +        Product(title: "", content: "", developerId: DeveloperID.Empty(), url: "", hashTags: [])
【全てはうらっしゅのせいなんだ。許してください。】
- バグの根源は、ProductのもつDeveloperがcreateされていないことが原因のエラーですね。
- Productは生成されているけどProductの開発者は登録処理がなかった。
- これで取得した時に、for文で見つからないdeveloperが、continueで抜けてしまっていたって感じです。

2024-06-23 15:11 UTC, urassh commented on Gitagram/Model/DataModel/Entity/Product.swift
> +        Product(title: "", content: "", developerId: DeveloperID.Empty(), url: "", hashTags: [])
一度うらっしゅ大反省会ができるくらいには重いとは思ってる。ごめんたー！！！！！！

2024-06-24 00:22 UTC, am2525nyan commented on Gitagram/Model/DataModel/Entity/Product.swift
> +        Product(title: "", content: "", developerId: DeveloperID.Empty(), url: "", hashTags: [])
うわーー！なるほど！loginHostが登録されてなかったんですね、、？
ついにごめんたー発動www修正感謝です！マージ！！！

と言いたいんですが、、、、マッチング画面のcardviewで見た時、url死んでます。。。firebase上で見た時には入っているので取得がうまくいってないのかと！大変申し訳ないんですが、ここも修正お願いします

<img src=https://github.com/ProgateHackathon/Gitagram/assets/115913702/46fe9682-8dfc-4d3a-8cd0-25aa5ca13263  width=30%>

2024-06-24 00:23 UTC, am2525nyan commented
あとカード部分のタグの修正ってどこかでやってたりしますー？

2024-06-25 15:03 UTC, urassh commented
@am2525nyan 
OpenLinkの不具合のやつ修正しておいたので、再度FBお願いします!!

2024-06-26 00:38 UTC, am2525nyan approved these changes
完璧すぎます！！！！！ありがとうございます！！！！！

2024-06-26 00:40 UTC, am2525nyan commented
@urassh 
めちゃめちゃいいです！！approveしました！
カード部分の修正これですー!　#72

2024-06-26 02:53 UTC, merged